name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create tagged release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package project
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            For changes, check the commit log.
          draft: false
          prerelease: false
      - name: Install conan
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          python3 -m venv ./conan_venv
          source ./conan_venv/bin/activate
          pip install conan
      - name: Create conan package
        working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          source ./conan_venv/bin/activate
          echo nngpp/${GITHUB_REF:11}@
          conan remote add petiaccja_public https://api.bintray.com/conan/petiaccja/public-conan
          conan user -p ${{ secrets.CONAN_BINTRAY_API_KEY }} -r petiaccja_public petiaccja
          conan create $GITHUB_WORKSPACE nngpp/${GITHUB_REF:11}@
          conan upload nngpp/${GITHUB_REF:11} --all --confirm -r petiaccja_public